### ISSUE TITLE
Manage -> ARM

### ISSUE THREAD

**Issue by jtaubensee** [Azure/azure-relay#11]

**Comment by tomkerkhove** [comment]
Any update on this?

**Comment by jfggdl** [comment]
Closing due to lack of understanding of the ask. Please feel free to reopen with more information.

**Comment by tomkerkhove** [comment]
The ask is for managing Azure Relay via ARM and not via portal - https://docs.microsoft.com/en-us/azure/service-bus-relay/relay-create-namespace-portal

If this is already the case, then the docs should be updated a bit to show where it's at.
