### ISSUE TITLE
Got this message "Unable to connect: The WebSocket protocol is not supported on this platform"

### ISSUE THREAD

**Issue by haiquan2009** [Azure/azure-relay#25]
Today I find the sample project [PortBridge](https://github.com/Azure/azure-relay/tree/master/samples/Hybrid%20Connections/DotNet/portbridge). And I have a try. When I run the project **PortBridgeServerAgent**, I get this message "Unable to connect: The WebSocket protocol is not supported on this platform". My platform is **Win7 x64**.

My question is:
1. Does it mean this solution PortBridge can not run on **Win7 x64**?
2. If the solution PortBridge really can not run on **Win7 x64**, is there any other solution with .NET, which can implement this tunneling feature and it can run on Win7 x32/x64. Thanks.

**Comment by ThiemeNL** [comment]
Any update on this?

**Comment by gdalsnes** [comment]
Any reason for not using SignalR in azure-relay?

**Comment by jfggdl** [comment]
@haiquan2009, please refer to  https://github.com/Azure/azure-relay-dotnet/issues/32#issuecomment-265032179.
