### ISSUE TITLE
PortBridge question

### ISSUE THREAD

**Issue by gsandorx** [Azure/azure-relay#26]
File: [https://github.com/Azure/azure-relay/blob/master/samples/Hybrid%20Connections/DotNet/portbridge/PortBridge/ServiceConnectionForwarder.cs](url)

Line: 120

Why are you guys making this recursive call here when the very same invocation is made on line 98?

**Comment by jfggdl** [comment]
@gsandorx, This is by design. As long as the service is running, it needs to listen for and accept new connections.
