### ISSUE TITLE
Incorrect Github License

### ISSUE THREAD

**Issue by coolhome** [Azure/azure-relay#32]
The code in the git repository is under `Apache License, Version 2.0` but the github repository says its `MIT`.

https://github.com/Azure/azure-relay/search?utf8=%E2%9C%93&q=Apache+License&type=

**Comment by jfggdl** [comment]
@coolhome, thank you for letting us know about this seemingly license discrepancy. We are looking into this. We will close this issue, but feel free to request to reopen it if you have more questions or comments.

**Comment by dlstucki** [comment]
(Closing on behalf of @jfggdl due to temporary permissions issues)
