### ISSUE TITLE
Sample on how to use a dynamic WCF relay from nodejs

### ISSUE THREAD

**Issue by gabog** [Azure/azure-relay#45]
Hello, is there a way of using a WCF relay from nodejs or JavaScript? 

I need a relay that I use occasionally and the pricing for WCF Relays fits my needs better than Hybrid connections.

My development platform is nodejs (my utility needs to run on windows and mac) but I only found examples on using WCF Relays for .Net framework. 

Are there any examples on how to do this from node?

Thanks

**Comment by dlstucki** [comment]
Do you need the Relay **Listener** to be in node.js or is the Relay **Sender** sufficient? If you only need the Sender to be in node.js then you can use something like WebHttpRelayBinding on the listener and plain-old HTTP/S for the Sender.

WcfRelay Listeners require WCF which is basically .NET Framework only (not even .NET Core).

**Comment by gabog** [comment]
Thanks for the kick reply @dlstucki, unfortunately, I need a listener. The issue is that Hybrid Connections are on all the time and that will cost me $9 a month whether I use it or not. 

The dynamic WCF relay gets dropped automatically when the listener drops which allows us to manage cost more efficiently. 

I could code my utility to create and drop a hybrid connection when it starts and ends but that could potentially leave me with an open hybrid connection if my process ends abnormally. 

Do you guys have a "Dynamic" hybrid connection planned? (probably not but it doesn't hurt to ask 😊)

**Comment by jfggdl** [comment]
@gabog, there is no plans for a "dynamic hybrid connection" feature. Would you please share with us how many listeners and how many hours a month you would need them approximately? What I would like to get is more context on the roadblocks that we might have with adoption of Hybrid Connections, which is our modern cross-language platform as it is based on open source technologies (web sockets).

**Comment by aslivker** [comment]
If you use API Management layer which natively support Azure Relay, then you can run your service on any platform and with no need to configure it with any Azure Relay knowledge, see here , https://nevatech.com/blog/post/Real-integration-of-API-Management-with-Azure-Service-Bus-Relay-Service

**Comment by jfggdl** [comment]
Thanks for the article and how through an API Management solution connections could be managed to lead to a lower Relay expense. 

We have had conversations on providing a different offering with better pricing for high-end consumption. We are not planning to implement what we are referring to "dynamic hybrid connections". Please let me know if your needs is to create thousands of listener connections and if you would be interested in a better pricing at a high-end consumption level.

**Comment by gabog** [comment]
Thanks @jfggdl, I am good for now, I will close this issue.
