### ISSUE TITLE
Strange relay behaviour in a high concurrency scenario (50 threads)

### ISSUE THREAD

**Issue by ccrego** [Azure/azure-relay#46]
# Description

Hi guys, we are building a platform which will allow to invoke an on-premise API from the cloud, for this purpose we are using WCF relays which in fact is the appropriate service for us since we need to create the relays on-demand (we have an onboarding API which is responsible for validating the customer license and creates the relay in Azure as part of this process).

At this moment our QA team is working on the load tests in order to know how much traffic supports the platform, during the tests our QA team detected a weird behaviour when they invoke a test case with 50 concurrent requests from JMeter.

Basically, in this scenario (50 concurrent requests), half of the requests fail because of 502 Bad Gateway and 504 Gateway Timeout responses.

The 502 Bad Gateway response comes from the relay, this response indicates that the listener didn't accept the connection within the allowed interval, this behaviour could be right since the listener is too much busy processing the concurrent requests, but the weird thing is that once we receive the 502 Bad Gateway response, no more requests reach the listener (the on-premise API), the only way to make the communication works again is to close the listener and start it again.

I have read the issue "#10 Scale" where is detailed the rendezvous algorithm as follows:

- Get a local copy of the list of all the known load-balanced listeners for the address requested by the sender (this comes from a cache which is updated every 500ms).
- If the list of listeners is empty and we haven't refreshed the list of listeners exactly once force refresh the list of known load-balanced listeners for the endpoint.
- If the list of listeners is empty return an exception to the sender and stop.
- Pick a random index into the list of potential listeners.
- Try to rendezvous with the selected listener.
- If that rendezvous succeeds then stop.
- If the rendezvous attempt with the selected listener doesn’t succeed within 10 seconds remove the selected listener from the list of listeners to try.
- If more than 60 seconds have passed return an exception to the sender.
- Go to step 2.

If the algorithm works in the way described above, then is very sensitive to DoS attacks, since once the rendezvous attempt fails, the listener will be removed from the list of listeners to try, this is a very bad idea since force to our customers to be aware of the load capacity and manage the windows service where is hosted the listener.

The funny thing is that we are applying the "ConnectionStatusBehaviour" to the endpoint to log whatever connection issue and we don't see anything strange in the logs, apparently, the service keeps connected/online.

There is some way to configure a different behaviour when the rendezvous attempt doesn't succeed within 10 seconds? Maybe some parameter which makes bigger the interval for accepting the connection?.

## Actual Binding Configuration (WebHttpRelayBinding)
1. SecurityMode = EndToEndWebHttpSecurityMode.Transport
2. RelayClientAuthenticationType  = RelayClientAuthenticationType.RelayAccessToken
3. IsDynamic = false
4. UseDefaultProxy = false
5. OpenTimeout = 10 seconds
6. CloseTimeout = 10 seconds
7. SendTimeout = 10 seconds
8. ReceiveTimeout = TimeSpan.MaxValue

## Actual ServiceThrottlingBehaviour Configuration
1. MaxConcurrentCalls = 160
2. MaxConcurrentInstances = 1000
3. MaxConcurrentSessions = 1160

## Actual Wcf Service Behaviour
InstanceContextMode = PerCall
ConcurencyMode = Single

## Client-side
The WCF relay is invoked from an AspNetCore 2.2 application using HttpClient since the relay address is discovered at runtime (we cannot use a WCF proxy in this case).

The AspNetCore application is hosted in Azure.

## Listener
Deployed on a Virtual Machine in Azure 
The system connectivity mode is configured with the value ConnectivityMode.Https

**Comment by dlstucki** [comment]
FYI, "remove the selected listener from the list" only affects the current rendezvous attempt. The list is local to that rendezvous attempt, nothing else.

**Comment by jfggdl** [comment]
@ccrego, would you please provide an update on your concerns?
