### ISSUE TITLE
Azure relay for Go

### ISSUE THREAD

**Issue by masters3d** [Azure/azure-relay#47]
I know there is already a service bus ask for golang. Are there any samples for using a azure relay listener in golang? I’m assuming I can send from he C# SDK to other listeners in other languages. 

# Description

## Actual Behavior
1. 
2. 

## Expected Behavior
1. 
2.

**Comment by jfggdl** [comment]
@masters3d,  Thank you for creating this issue. We do not have support for Go SDKs/samples for Azure Relay. That said, we will be tracking the interest on this feature for future planning. I am going to close this issue now, but feel free to request to be reopen if you have any question.

**Comment by dlstucki** [comment]
(Closing on behalf of @jfggdl due to temporary permissions issues)
