### ISSUE TITLE
Azure Hybrid Connection Reliability vs Service Bus Reliability

### ISSUE THREAD

**Issue by Sudhanshus2020** [Azure/azure-relay#51]
# Description

Is there any difference between Azure Hybrid Connection Reliability vs Service Bus Reliability.

## Actual Behavior
1. I don't know

## Expected Behavior
1.  I am expecting same reliability, please let me know.

**Comment by jfggdl** [comment]
@Sudhanshus2020, thanks for your question. SLAs offered are documented in the following page:

https://azure.microsoft.com/en-us/support/legal/sla/service-bus/v1_1/

As you can see, the up time SLA for for Relay and Service Bus is currently the same at 99.9%.

When the post refers to "...Service Bus Relays..." in the following SLA statement, it refers to both WCF  Relays and Hybrid Connections Relays.

"For Service Bus Relays, we guarantee that at least 99.9% of the time, properly configured applications will be able to establish a connection to a deployed Relay."

I hope this addresses your question. Please let me know if you have any more question.

**Comment by Sudhanshus2020** [comment]
> @Sudhanshus2020, thanks for your question. SLAs offered are documented in the following page:
> 
> https://azure.microsoft.com/en-us/support/legal/sla/service-bus/v1_1/
> 
> As you can see, the up time SLA for for Relay and Service Bus is currently the same at 99.9%.
> 
> When the post refers to "...Service Bus Relays..." in the following SLA statement, it refers to both WCF Relays and Hybrid Connections Relays.
> 
> "For Service Bus Relays, we guarantee that at least 99.9% of the time, properly configured applications will be able to establish a connection to a deployed Relay."
> 
> I hope this addresses your question. Please let me know if you have any more question.

Thanks for Response.
Perfect Answer.
